# 自定义掉落 CustomDrop 插件
# 作者：Month_Light

# 插件版本号
version: 1.0

# 插件的前缀
Prefix: '&f[&b自定义掉落&f] '

# 插件消息配置
Messages:
    # 注意可以修改文本，但是不要修改里面的格式符 %1$s，%2$s 等
    NoPermission: '&c你没有使用这个命令的权限.'
    ErrorCommandArgs: '&c未知的命令参数，请使用: %1$s'
    CustomDropReload: '&a配置文件已经重新载入...'
    GrantCustomDropMoney: '&6从目标%2$s上获得 &a%1$s &6掉落金币.'

# 方块自定义掉落设置
#
# STONE: # 当破坏石头掉落的表
#   - 'drop-example.yml'
#
# STONE-6: # 当破坏磨制安山岩掉落的表
#   - 'drop-example.yml'
#
BlockList: []

# 实体自定义掉落设置
#
# CREEPER: # 当杀死苦力怕掉落的表
#   - 'drop-example.yml'
#
MobList: []
